# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0004_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('startDate', models.CharField(max_length=255)),
                ('endDate', models.CharField(max_length=255)),
                ('traveler', models.ManyToManyField(related_name='users', to='login_app.User')),
            ],
        ),
    ]
