# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20171026_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
